server:
  port: 0

spring:
  application:
    name: product-service

  datasource:
    url: jdbc:mysql://localhost:3306/product?serverTimezone=Asia/Seoul
    username: root
    password: 1q2w3e4r!!

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

  server:
    enable-self-preservation: false

#temp
jwt:
  secret: fewbiuebeot5324980hbhgsd0uub9gpkklnqbp4214989oub926t32be0gbdsn