
server:
  port: 0

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://localhost:3306/product?serverTimezone=Asia/Seoul
    username: root
    password: 1q2w3e4r!!
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

jwt:
  secret: fewbiuebeot5324980hbhgsd0uub9gpkklnqbp4214989oub926t32be0gbdsn

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.184:8761/eureka
  instance:
    prefer-ip-address: true